import type { Metadata } from "next";
import { Geist, Geist_Mono, Cairo, Poppins } from "next/font/google";
import "./globals.css";
import StarCursor from "@/components/StarCursor";
import Starfield from "@/components/Starfield";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic", "latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${cairo.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="relative min-h-full flex flex-col bg-[#070312] text-white">
        {/* GLOBAL BACKGROUND CANVAS */}
        <Starfield />

        {/* CUSTOM CURSOR */}
        <StarCursor />

        {/* PAGE CONTENT */}
        <div className="relative z-10 flex flex-col flex-1">{children}</div>
      </body>
    </html>
  );
}